name: Publish to Registry

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        default: '0.0.0'
        required: true

jobs:
  build:
    runs-on: windows-latest
    if: github.ref == 'refs/heads/net5'

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Restore
      run: dotnet restore ExceptionReporter.NET.sln
      
    #- name: Add msbuild to PATH
    #  uses: microsoft/setup-msbuild@v1.1

    - name: Pack Managed Libraries
      run: dotnet pack src/ExceptionReporter.WinForms/ExceptionReporter.WinForms.csproj --configuration Release -p:PackageVersion=${{github.event.inputs.version}}

    - name: Publish the package to GPR
      run: dotnet nuget push "src/ExceptionReporter.WinForms/bin/Release/ExceptionReporter.${{github.event.inputs.version}}.nupkg"
      #run: dotnet nuget push src/ExceptionReporter.WinForms/.dist/ExceptionReporter.WinForms.${{github.event.inputs.version}}.nupkg
