name: Publish to Registry

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        default: '1.0.0'
        required: true

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: windows-latest
    if: github.ref == 'refs/heads/net5'

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        
    - name: Restore
      run: dotnet restore
      
    - name: 'Build'
      run: dotnet build --configuration Release --no-restore
    
    - name: Pack Managed Libraries
      run: dotnet pack --no-build src/ExceptionReporter.WinForms/ExceptionReporter.WinForms.csproj --configuration Release -p:PackageVersion=${{github.event.inputs.version}}

    - name: 'Dotnet NuGet Add Source'
      run: dotnet nuget add source https://nuget.pkg.github.com/PauloHMattos/index.json --name GitHub --username PauloHMattos --password ${{secrets.GITHUB_TOKEN}}
      shell: pwsh
      
    - name: 'Dotnet NuGet Push'
      run: dotnet nuget push src\ExceptionReporter.WinForms\bin\Release\ExceptionReporter.${{github.event.inputs.version}}.nupkg --api-key ${{ github.token }} --source GitHub --skip-duplicate
      shell: pwsh
