name: Publish to Registry

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        default: '0.0.0'
        required: true

jobs:
  build:
    runs-on: windows-latest
    if: github.ref == 'refs/heads/net5'

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Restore
      run: dotnet restore src/ExceptionReporter.NET.sln

    - name: Pack
      run: msbuild src/ExceptionReporter.WinForms/ExceptionReporter.WinForms.csproj /t:pack -p:Configuration=Release -p:PackageVersion=${{github.event.inputs.version}} -p:OutputPath=.dist -t:restore -p:RestorePackagesConfig=true

    - name: Push
      run: dotnet nuget push src/D2DLibExport/.dist/ExceptionReporter.WinForms.${{github.event.inputs.version}}.nupkg --api-key ${{secrets.NUGET_API_KEY}} -s https://nuget.pkg.github.com/LAMCSO/index.json --skip-duplicate
        
